### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by climaxxx2** [shimuldn/hCaptchaSolverApi#15]
Nice work.
In selenium this must be with # 

if r.json()['success']:
            for item in images_div:
                name=item.get_attribute("aria-label")
                nn=int(name.replace("Challenge Image ", ""))-1
                if r.json()['solution'][str(nn)]:
                    time.sleep(0.05)
                    item.click()

            time.sleep(20)
            WebDriverWait(driver, 35, ignored_exceptions=ElementClickInterceptedException).until(
                EC.element_to_be_clickable((By.XPATH, "//div[@class='button-submit button']"))
            ).click()

And when theres a seaplane the requests goes on infinite loop. I don.t know why
Great anyways.

**Comment by shimuldn** [comment]
Seaplane fixed.
A GitHub start is another way to say thanks.

**Comment by shimuldn** [comment]
> Nice work. In selenium this must be with

I am straggling with selenium. If you want, you can create a pull request with updated selenium example.
Can i close this issue?

**Comment by climaxxx2** [comment]
> > Nice work. In selenium this must be with
> 
> I am straggling with selenium. If you want, you can create a pull request with updated selenium example. Can i close this issue?

Lol. Mee too. But yes. You can close.

**Comment by shimuldn** [comment]
Good luck 🤞.
Please create a new issue if there any.
Feedback and suggestions are appreciated 😊.
