### ISSUE TITLE
Account signup, verification, free usage?

### ISSUE THREAD

**Issue by shimuldn** [shimuldn/hCaptchaSolverApi#26]
Please stop!
Just received 700 new user in an hour? Should i be happy about it?
I'm still giving this for free while in beta. And even will give for free after. So why so much spam!! 😓 

This is an AI repo, just a command away to block all temp mail. Spamming will only make me restrict the usage more and more. So do at your own consciousness, spam will only enable me.

*** Only one account per person.
*** No temp email signup will be accepted from now on.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/12117121/180894479-2ab9d4a8-7b83-4221-934e-024941a01516.png">

**Comment by shimuldn** [comment]
Clean Up completed!

**Comment by viniciusvj** [comment]
I need to use 1000 requests more, do you have other plans and pricing?

**Comment by viniciusvj** [comment]
I need to use 1000 requests more, do you have other plans and pricing?

**Comment by debpalash** [comment]
> I need to use 1000 requests more, do you have other plans and pricing?

We're working on website but you can talk to us for your requirements https://discord.gg/WzuvmHxd or captcha@shimul.me
