### ISSUE TITLE
user id or email already exist.

### ISSUE THREAD

**Issue by bntr00t** [shimuldn/hCaptchaSolverApi#27]
tested with multiple emails and user ids
{"error_code": 409, "status": "user id or email already exist."}

**Comment by OpenSource03** [comment]
I'm experiencing this issue as well.

**Comment by debpalash** [comment]
Signup has been disable temporally, will be enable after some security update. Tune in our discord for quick updates. @bntr00t @OpenSource03

**Comment by shimuldn** [comment]
Signup re-enabled.  Remember no temp-mail. Temp-mail = ban permanently.
