### ISSUE TITLE
Please improve image api

### ISSUE THREAD

**Issue by tzbo** [shimuldn/hCaptchaSolverApi#29]
Please refer [Yescaptcha](https://yescaptcha.atlassian.net/wiki/spaces/YESCAPTCHA/pages/28344322/Hcaptcha)

I just want request with image type with all 18 images. And I wish it can be faster than Yescaptcha which could response solution within 8 seconds.

Ofcourse, I can pay for good service.

**Comment by shimuldn** [comment]
We will implement 18 images in next few days. Join my server to get notified https://discord.gg/E7FfzhZqzA

**Comment by tzbo** [comment]
Okay, I just want to request with base64 encoded images and challenge question. Please refer Yescaptcha.

**Comment by shimuldn** [comment]
Will do that too.

**Comment by shimuldn** [comment]
Started working on it. Will give you an update after doing some test.

**Comment by tzbo** [comment]
You can publish to npm. I update to a new version.

**Comment by shimuldn** [comment]
> You can update the doc. I will test it.
> 
> I will compare with another service.

Can you send me ping on discord ?

**Comment by tzbo** [comment]
Is this improvement updated?

**Comment by shimuldn** [comment]
> Is this improvement updated?

Implementation already done, just waiting for docs to be updated.

Just send a request format as bellow JSON. All others things are same.
https://raw.githubusercontent.com/shimuldn/hCaptchaSolverApi/main/usage_examples/base64-body-format.json

Note: target related to dog ..., lion ... arr not available on free version. Also, solving accuracy is huge different on free.

Will update the accuracy info for paid and free soon.
If you want to compare paid API, please contact discord or telegram for a free trial also fast response!

Thanks

**Comment by tzbo** [comment]
Okay, I think siteKey and site are not needed for this API.
