### ISSUE TITLE
Hi my ApiKey doesnt work

### ISSUE THREAD

**Issue by TarekMadara** [shimuldn/hCaptchaSolverApi#39]
Hello guys, i don't know why my apiKey and uid doesnt work and keep getting this json response:
{'message': 'apikey is missing', 'status': 'Unauthorized'}

(I am certain that the apikey and uid are the same that you sended me through the Email)
Please help

Best regards.

**Comment by shimuldn** [comment]
In this case, we need to check your UID. Please contact me on https://discord.gg/E7FfzhZqzA or email ai@shimul.me with your email and UID.

**Comment by shimuldn** [comment]
Issue fixed.
